---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url:
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_docker_image: forestryio/ruby:2.6
  install_dependencies_command: bundle install --path vendor/bundle
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future -d _site
  mount_path: "/srv"
  working_dir: "/srv"
  preview_output_directory: "_site"
  preview_env:
    - JEKYLL_ENV=staging
