---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: home
  label: Home
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: temp-images
public_path: "/temp-images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: ""
  working_dir: "/_site"
  preview_output_directory: "/_site"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
