---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: "/srv"
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn start
